spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/onsitesurveydemo
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/kotlin
      exclude: static/**,public/**,templates/**

# Swagger(OpenAPI) 기본 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
